import Foundation

nonisolated extension ExerciseLibrary {
    static let chestExercises: [Exercise] = [
        ExerciseBuilder.make("barbell-bench-press", "Barbell Bench Press", primary: .chest, secondary: [.triceps, .shoulders], move: .horizontalPush, equip: [.barbell, .bench], diff: .intermediate, desc: "The king of chest exercises. Builds overall chest mass and pressing strength.", instructions: ["Lie on bench with eyes under bar", "Grip bar slightly wider than shoulders", "Unrack and lower to mid-chest", "Press up to lockout"], mistakes: ["Bouncing bar off chest", "Flaring elbows too wide", "Lifting hips off bench"], cues: ["Drive feet into floor", "Squeeze shoulder blades together", "Control the descent"], alts: ["dumbbell-bench-press", "machine-chest-press"], tags: ["strength", "mass", "powerlifting"]),
        ExerciseBuilder.make("dumbbell-bench-press", "Dumbbell Bench Press", primary: .chest, secondary: [.triceps, .shoulders], move: .horizontalPush, equip: [.dumbbell, .bench], beginnerOk: true, desc: "Greater range of motion than barbell. Excellent for chest development.", instructions: ["Sit on bench with dumbbells on thighs", "Lie back and press dumbbells up", "Lower with control to chest level", "Press back up squeezing chest"], mistakes: ["Going too heavy too fast", "Not controlling the negative"], cues: ["Feel the stretch at the bottom", "Press in a slight arc"], alts: ["barbell-bench-press", "machine-chest-press"], tags: ["mass", "hypertrophy"]),
        ExerciseBuilder.make("incline-barbell-press", "Incline Barbell Press", primary: .chest, secondary: [.shoulders, .triceps], move: .horizontalPush, equip: [.barbell, .bench], desc: "Targets upper chest for a fuller, more complete chest.", instructions: ["Set bench to 30-45 degree incline", "Grip bar shoulder-width plus", "Lower to upper chest", "Press to lockout"], mistakes: ["Bench angle too steep", "Excessive arch"], cues: ["Drive through upper chest", "Keep shoulder blades pinched"], alts: ["incline-dumbbell-press", "incline-machine-press"], tags: ["upper chest", "mass"]),
        ExerciseBuilder.make("incline-dumbbell-press", "Incline Dumbbell Press", primary: .chest, secondary: [.shoulders, .triceps], move: .horizontalPush, equip: [.dumbbell, .bench], beginnerOk: true, desc: "Excellent upper chest builder with greater range of motion.", instructions: ["Set bench to 30-45 degrees", "Press dumbbells up from shoulders", "Lower with control", "Squeeze at top"], mistakes: ["Too steep an incline"], cues: ["Feel upper chest working"], alts: ["incline-barbell-press"], tags: ["upper chest"]),
        ExerciseBuilder.make("decline-dumbbell-press", "Decline Dumbbell Press", primary: .chest, secondary: [.triceps], move: .horizontalPush, equip: [.dumbbell, .bench], desc: "Targets lower chest fibers.", instructions: ["Set bench to decline", "Press dumbbells overhead", "Lower to lower chest", "Press back up"], alts: ["decline-barbell-press", "dips"], tags: ["lower chest"]),
        ExerciseBuilder.make("machine-chest-press", "Machine Chest Press", primary: .chest, secondary: [.triceps, .shoulders], cat: .isolation, move: .horizontalPush, equip: [.machine], beginnerOk: true, desc: "Safe, guided chest press. Great for beginners and burnout sets.", instructions: ["Adjust seat height", "Grip handles at chest level", "Press forward to full extension", "Return with control"], cues: ["Squeeze chest at extension"], alts: ["barbell-bench-press", "dumbbell-bench-press"], tags: ["beginner", "safe"]),
        ExerciseBuilder.make("incline-machine-press", "Incline Machine Chest Press", primary: .chest, secondary: [.shoulders, .triceps], cat: .isolation, move: .horizontalPush, equip: [.machine], beginnerOk: true, desc: "Machine-guided upper chest press for safe, controlled movement.", alts: ["incline-dumbbell-press"], tags: ["upper chest", "beginner"]),
        ExerciseBuilder.make("cable-chest-fly", "Cable Chest Fly", primary: .chest, cat: .isolation, move: .horizontalPush, equip: [.cable], desc: "Constant tension through the full range. Great chest isolation.", instructions: ["Set pulleys to shoulder height", "Step forward slightly", "Bring handles together in arc", "Squeeze chest at peak contraction"], mistakes: ["Using too much weight", "Bending arms excessively"], cues: ["Think hugging a tree", "Squeeze at the center"], alts: ["dumbbell-fly", "pec-deck"], tags: ["isolation", "pump"]),
        ExerciseBuilder.make("dumbbell-fly", "Dumbbell Fly", primary: .chest, cat: .isolation, move: .horizontalPush, equip: [.dumbbell, .bench], desc: "Classic chest isolation. Stretches and contracts the pecs.", instructions: ["Lie on bench with dumbbells overhead", "Lower in wide arc with slight bend", "Feel deep stretch", "Bring back up squeezing chest"], mistakes: ["Going too heavy", "Straightening arms completely"], alts: ["cable-chest-fly", "pec-deck"], tags: ["isolation", "stretch"]),
        ExerciseBuilder.make("pec-deck", "Pec Deck Machine", primary: .chest, cat: .isolation, move: .horizontalPush, equip: [.machine], beginnerOk: true, desc: "Machine fly variation. Safe chest isolation.", alts: ["cable-chest-fly", "dumbbell-fly"], tags: ["isolation", "beginner"]),
        ExerciseBuilder.make("push-up", "Push-Up", primary: .chest, secondary: [.triceps, .shoulders, .coreStability], cat: .bodyweight, move: .horizontalPush, worlds: [.homeNoEquipment, .calisthenics, .warmupActivation], equip: [.none], loc: .anywhere, diff: .beginner, beginnerOk: true, bw: true, desc: "The foundational bodyweight push. Works chest, shoulders, and triceps.", instructions: ["Hands shoulder-width on floor", "Body in straight line", "Lower chest to floor", "Push back up to start"], mistakes: ["Sagging hips", "Flaring elbows too wide", "Not going deep enough"], cues: ["Keep core tight", "Elbows at 45 degrees"], alts: ["knee-push-up", "incline-push-up"], tags: ["bodyweight", "fundamental"]),
        ExerciseBuilder.make("knee-push-up", "Knee Push-Up", primary: .chest, secondary: [.triceps, .shoulders], cat: .bodyweight, move: .horizontalPush, worlds: [.homeNoEquipment, .calisthenics], equip: [.none], loc: .anywhere, diff: .beginner, beginnerOk: true, bw: true, prog: .regression, regOf: "push-up", desc: "Easier push-up variation for beginners.", alts: ["push-up", "incline-push-up"], tags: ["beginner", "regression"]),
        ExerciseBuilder.make("incline-push-up", "Incline Push-Up", primary: .chest, secondary: [.triceps, .shoulders], cat: .bodyweight, move: .horizontalPush, worlds: [.homeNoEquipment, .calisthenics], equip: [.none], loc: .anywhere, diff: .beginner, beginnerOk: true, bw: true, prog: .regression, desc: "Hands elevated push-up. Easier than standard.", alts: ["push-up", "knee-push-up"], tags: ["beginner", "regression"]),
        ExerciseBuilder.make("decline-push-up", "Decline Push-Up", primary: .chest, secondary: [.shoulders, .triceps], cat: .bodyweight, move: .horizontalPush, worlds: [.homeNoEquipment, .calisthenics], equip: [.none], loc: .anywhere, diff: .intermediate, bw: true, prog: .progression, progOf: "push-up", desc: "Feet elevated push-up targeting upper chest.", alts: ["push-up", "diamond-push-up"], tags: ["progression", "upper chest"]),
        ExerciseBuilder.make("diamond-push-up", "Diamond Push-Up", primary: .chest, secondary: [.triceps], cat: .bodyweight, move: .horizontalPush, worlds: [.homeNoEquipment, .calisthenics], equip: [.none], loc: .anywhere, diff: .intermediate, bw: true, prog: .progression, progOf: "push-up", desc: "Close-grip push-up emphasizing triceps and inner chest.", alts: ["push-up", "close-grip-bench"], tags: ["triceps", "progression"]),
        ExerciseBuilder.make("dips", "Dips", primary: .chest, secondary: [.triceps, .shoulders], cat: .bodyweight, move: .horizontalPush, worlds: [.gymStrength, .calisthenics], equip: [.dipStation], diff: .intermediate, bw: true, desc: "Powerful compound for lower chest and triceps.", instructions: ["Grip dip bars and support yourself", "Lean slightly forward for chest focus", "Lower until upper arms parallel", "Press back up"], mistakes: ["Going too deep", "Not leaning forward"], cues: ["Lean forward for chest", "Stay upright for triceps"], alts: ["machine-dip", "bench-dip"], tags: ["compound", "mass"]),
        ExerciseBuilder.make("machine-dip", "Machine Dip", primary: .chest, secondary: [.triceps], cat: .compound, move: .horizontalPush, equip: [.machine], beginnerOk: true, prog: .regression, regOf: "dips", desc: "Assisted dip machine for building up to bodyweight dips.", alts: ["dips", "bench-dip"], tags: ["beginner", "assisted"]),
        ExerciseBuilder.make("bench-dip", "Bench Dip", primary: .triceps, secondary: [.chest, .shoulders], cat: .bodyweight, move: .horizontalPush, worlds: [.homeNoEquipment], equip: [.bench], loc: .anywhere, diff: .beginner, beginnerOk: true, bw: true, desc: "Tricep-focused dip using a bench or chair.", alts: ["dips", "machine-dip"], tags: ["beginner", "home"]),
        ExerciseBuilder.make("cable-crossover", "Cable Crossover", primary: .chest, cat: .isolation, move: .horizontalPush, equip: [.cable], desc: "High-to-low cable fly targeting lower chest.", instructions: ["Set cables high", "Step forward into split stance", "Pull handles down and together", "Squeeze at bottom"], alts: ["cable-chest-fly", "dumbbell-fly"], tags: ["isolation", "lower chest"]),
        ExerciseBuilder.make("landmine-press", "Landmine Press", primary: .chest, secondary: [.shoulders, .triceps], move: .horizontalPush, equip: [.barbell], desc: "Angled press with a barbell anchored in a corner. Shoulder-friendly.", alts: ["incline-dumbbell-press"], tags: ["shoulder-friendly", "functional"]),
        ExerciseBuilder.make("svend-press", "Svend Press", primary: .chest, cat: .isolation, move: .horizontalPush, worlds: [.gymStrength, .homeGym], equip: [.dumbbell], beginnerOk: true, desc: "Light plate squeeze press for chest activation and pump.", alts: ["cable-chest-fly"], tags: ["activation", "pump"]),
        ExerciseBuilder.make("floor-press-barbell", "Barbell Floor Press", primary: .chest, secondary: [.triceps], move: .horizontalPush, equip: [.barbell], jointFriendly: true, desc: "Bench press from the floor. Limits range of motion for shoulder safety and lockout strength.", instructions: ["Lie on floor with barbell overhead", "Grip slightly wider than shoulders", "Lower until triceps touch floor", "Press back to lockout"], cues: ["Pause briefly on floor", "Drive through triceps"], alts: ["barbell-bench-press", "floor-press-dumbbell"], tags: ["shoulder-friendly", "lockout"]),
        ExerciseBuilder.make("floor-press-dumbbell", "Dumbbell Floor Press", primary: .chest, secondary: [.triceps], move: .horizontalPush, worlds: [.gymStrength, .homeGym], equip: [.dumbbell], beginnerOk: true, jointFriendly: true, desc: "Dumbbell press from the floor. Great for shoulder safety and home training.", alts: ["dumbbell-bench-press", "floor-press-barbell"], tags: ["shoulder-friendly", "home"]),
        ExerciseBuilder.make("smith-incline-press", "Smith Machine Incline Press", primary: .chest, secondary: [.shoulders, .triceps], move: .horizontalPush, equip: [.smithMachine], beginnerOk: true, desc: "Guided incline press on Smith machine for safe upper chest work.", alts: ["incline-barbell-press", "incline-machine-press"], tags: ["guided", "upper chest"]),
        ExerciseBuilder.make("low-incline-dumbbell-press", "Low Incline Dumbbell Press", primary: .chest, secondary: [.shoulders, .triceps], move: .horizontalPush, equip: [.dumbbell, .bench], beginnerOk: true, jointFriendly: true, desc: "15-20 degree incline for upper chest emphasis with less shoulder strain.", instructions: ["Set bench to low incline (15-20 degrees)", "Press dumbbells from shoulder level", "Lower with control", "Focus on upper chest squeeze"], alts: ["incline-dumbbell-press"], tags: ["upper chest", "shoulder-friendly"]),
        ExerciseBuilder.make("incline-cable-fly", "Incline Cable Fly", primary: .chest, cat: .isolation, move: .horizontalPush, equip: [.cable, .bench], desc: "Incline fly using cables for constant tension on upper chest.", alts: ["cable-chest-fly", "incline-dumbbell-press"], tags: ["upper chest", "isolation"]),
        ExerciseBuilder.make("wide-push-up", "Wide Push-Up", primary: .chest, secondary: [.shoulders], cat: .bodyweight, move: .horizontalPush, worlds: [.homeNoEquipment, .calisthenics], equip: [.none], loc: .anywhere, diff: .beginner, beginnerOk: true, bw: true, desc: "Wide hand placement push-up for greater chest stretch.", alts: ["push-up", "dumbbell-fly"], tags: ["bodyweight", "chest stretch"]),
        ExerciseBuilder.make("explosive-push-up", "Explosive Push-Up", primary: .chest, secondary: [.triceps, .shoulders], cat: .bodyweight, move: .horizontalPush, worlds: [.calisthenics, .functionalAthletic], equip: [.none], loc: .anywhere, diff: .advanced, bw: true, prog: .progression, progOf: "push-up", desc: "Push off the ground with enough force to lift hands. Power and fast-twitch chest.", alts: ["push-up", "decline-push-up"], tags: ["power", "plyometric", "advanced"]),
    ]
}
