import Foundation

nonisolated extension ExerciseLibrary {
    static let coreExercises: [Exercise] = [
        ExerciseBuilder.make("plank", "Plank", primary: .coreStability, secondary: [.abs, .shoulders], cat: .bodyweight, move: .isometric, worlds: [.homeNoEquipment, .warmupActivation, .calisthenics], equip: [.none], loc: .anywhere, diff: .beginner, beginnerOk: true, bw: true, jointFriendly: true, desc: "Isometric core hold. Foundation of core training.", instructions: ["Forearms and toes on floor", "Body in straight line", "Brace core", "Hold position"], mistakes: ["Hips sagging", "Hips too high", "Holding breath"], cues: ["Squeeze glutes", "Draw belly button in", "Breathe steadily"], alts: ["side-plank", "dead-bug"], tags: ["fundamental", "isometric", "core"]),
        ExerciseBuilder.make("side-plank", "Side Plank", primary: .obliques, secondary: [.coreStability], cat: .bodyweight, move: .isometric, worlds: [.homeNoEquipment, .calisthenics], equip: [.none], loc: .anywhere, diff: .beginner, beginnerOk: true, bw: true, jointFriendly: true, desc: "Lateral core stability hold.", alts: ["plank", "oblique-crunch"], tags: ["obliques", "stability"]),
        ExerciseBuilder.make("crunch", "Crunch", primary: .abs, cat: .bodyweight, move: .flexion, worlds: [.homeNoEquipment], equip: [.none], loc: .anywhere, diff: .beginner, beginnerOk: true, bw: true, jointFriendly: true, desc: "Basic abdominal crunch. Controlled upper ab contraction.", instructions: ["Lie on back, knees bent", "Curl shoulders off floor", "Squeeze abs at top", "Lower with control"], mistakes: ["Pulling on neck", "Using momentum"], cues: ["Hands behind head lightly", "Exhale on the way up"], alts: ["cable-crunch", "sit-up"], tags: ["abs", "fundamental"]),
        ExerciseBuilder.make("cable-crunch", "Cable Crunch", primary: .abs, cat: .isolation, move: .flexion, equip: [.cable], desc: "Kneeling cable crunch for loaded ab work.", instructions: ["Kneel facing cable", "Hold rope behind head", "Crunch down bringing elbows to knees", "Control the return"], alts: ["crunch", "machine-crunch"], tags: ["abs", "loaded"]),
        ExerciseBuilder.make("machine-crunch", "Machine Ab Crunch", primary: .abs, cat: .isolation, move: .flexion, equip: [.machine], beginnerOk: true, desc: "Guided machine crunch for beginners.", alts: ["cable-crunch", "crunch"], tags: ["beginner", "machine"]),
        ExerciseBuilder.make("sit-up", "Sit-Up", primary: .abs, secondary: [.hipFlexors], cat: .bodyweight, move: .flexion, worlds: [.homeNoEquipment], equip: [.none], loc: .anywhere, diff: .beginner, beginnerOk: true, bw: true, desc: "Full sit-up from floor.", alts: ["crunch"], tags: ["abs", "classic"]),
        ExerciseBuilder.make("hanging-leg-raise", "Hanging Leg Raise", primary: .abs, secondary: [.hipFlexors], cat: .bodyweight, move: .flexion, worlds: [.gymStrength, .calisthenics], equip: [.pullUpBar], diff: .intermediate, bw: true, desc: "Hanging from bar, raise straight legs. Advanced ab exercise.", instructions: ["Hang from pull-up bar", "Raise legs to parallel or higher", "Lower with control", "Avoid swinging"], alts: ["lying-leg-raise", "hip-flexor-raise"], tags: ["advanced", "lower abs"]),
        ExerciseBuilder.make("lying-leg-raise", "Lying Leg Raise", primary: .abs, secondary: [.hipFlexors], cat: .bodyweight, move: .flexion, worlds: [.homeNoEquipment], equip: [.none], loc: .anywhere, diff: .beginner, beginnerOk: true, bw: true, desc: "Lying on back, raise legs for lower abs.", alts: ["hanging-leg-raise"], tags: ["lower abs", "beginner"]),
        ExerciseBuilder.make("russian-twist", "Russian Twist", primary: .obliques, secondary: [.abs], cat: .bodyweight, move: .rotation, worlds: [.homeNoEquipment, .functionalAthletic], equip: [.none], loc: .anywhere, diff: .beginner, beginnerOk: true, bw: true, desc: "Seated rotation with or without weight for obliques.", instructions: ["Sit with knees bent, lean back slightly", "Rotate torso side to side", "Touch floor on each side", "Keep core engaged"], alts: ["woodchop", "bicycle-crunch"], tags: ["obliques", "rotation"]),
        ExerciseBuilder.make("bicycle-crunch", "Bicycle Crunch", primary: .abs, secondary: [.obliques], cat: .bodyweight, move: .rotation, worlds: [.homeNoEquipment], equip: [.none], loc: .anywhere, diff: .beginner, beginnerOk: true, bw: true, desc: "Alternating knee-to-elbow crunch.", instructions: ["Lie on back, hands behind head", "Bring opposite elbow to knee", "Extend other leg", "Alternate continuously"], alts: ["russian-twist", "crunch"], tags: ["abs", "obliques"]),
        ExerciseBuilder.make("woodchop", "Cable Woodchop", primary: .obliques, secondary: [.coreStability, .rotationAntiRotation], cat: .compound, move: .rotation, equip: [.cable], desc: "Diagonal cable chop for rotational core power.", instructions: ["Set cable high or low", "Pull diagonally across body", "Rotate through core", "Control the return"], alts: ["russian-twist", "medicine-ball-slam"], tags: ["rotation", "functional", "power"]),
        ExerciseBuilder.make("pallof-press", "Pallof Press", primary: .rotationAntiRotation, secondary: [.coreStability], cat: .isolation, move: .antiRotation, equip: [.cable], beginnerOk: true, jointFriendly: true, desc: "Anti-rotation press for core stability.", instructions: ["Stand sideways to cable at chest height", "Press handle straight out", "Resist the rotation", "Hold and return"], alts: ["plank", "dead-bug"], tags: ["anti-rotation", "stability", "functional"]),
        ExerciseBuilder.make("dead-bug", "Dead Bug", primary: .coreStability, secondary: [.abs], cat: .bodyweight, move: .antiRotation, worlds: [.homeNoEquipment, .warmupActivation, .recoveryRehab], equip: [.none], loc: .anywhere, diff: .beginner, beginnerOk: true, bw: true, jointFriendly: true, desc: "Alternating arm/leg extension from supine. Core stability essential.", instructions: ["Lie on back, arms up, knees at 90", "Extend opposite arm and leg", "Keep lower back pressed into floor", "Return and alternate"], alts: ["bird-dog", "plank"], tags: ["stability", "rehab", "fundamental"]),
        ExerciseBuilder.make("bird-dog", "Bird Dog", primary: .coreStability, secondary: [.lowerBack, .glutes], cat: .bodyweight, move: .antiRotation, worlds: [.homeNoEquipment, .warmupActivation, .recoveryRehab], equip: [.none], loc: .anywhere, diff: .beginner, beginnerOk: true, bw: true, jointFriendly: true, desc: "Opposite arm and leg extension from all fours.", alts: ["dead-bug", "plank"], tags: ["stability", "rehab", "balance"]),
        ExerciseBuilder.make("ab-wheel-rollout", "Ab Wheel Rollout", primary: .abs, secondary: [.coreStability, .lats], cat: .bodyweight, move: .flexion, worlds: [.gymStrength, .homeGym], equip: [.abWheel], diff: .intermediate, bw: true, desc: "Roll out on ab wheel for intense core work.", alts: ["plank", "hanging-leg-raise"], tags: ["advanced", "abs"]),
        ExerciseBuilder.make("mountain-climber", "Mountain Climber", primary: .abs, secondary: [.coreStability, .hipFlexors], cat: .bodyweight, move: .flexion, worlds: [.homeNoEquipment, .cardioConditioning, .warmupActivation], equip: [.none], loc: .anywhere, diff: .beginner, beginnerOk: true, bw: true, desc: "Dynamic plank with alternating knee drives. Cardio and core.", alts: ["plank", "burpee"], tags: ["cardio", "core", "dynamic"]),
        ExerciseBuilder.make("v-up", "V-Up", primary: .abs, cat: .bodyweight, move: .flexion, worlds: [.homeNoEquipment, .calisthenics], equip: [.none], loc: .anywhere, diff: .intermediate, bw: true, desc: "Simultaneous upper and lower body crunch forming a V.", alts: ["crunch", "hanging-leg-raise"], tags: ["abs", "advanced"]),
        ExerciseBuilder.make("flutter-kick", "Flutter Kicks", primary: .abs, secondary: [.hipFlexors], cat: .bodyweight, move: .flexion, worlds: [.homeNoEquipment], equip: [.none], loc: .anywhere, diff: .beginner, beginnerOk: true, bw: true, desc: "Alternating small leg kicks while lying on back.", alts: ["lying-leg-raise"], tags: ["lower abs", "endurance"]),
        ExerciseBuilder.make("toe-touch", "Toe Touch Crunch", primary: .abs, cat: .bodyweight, move: .flexion, worlds: [.homeNoEquipment], equip: [.none], loc: .anywhere, diff: .beginner, beginnerOk: true, bw: true, desc: "Reach hands to elevated feet for ab crunch.", alts: ["crunch", "v-up"], tags: ["abs"]),
        ExerciseBuilder.make("medicine-ball-slam", "Medicine Ball Slam", primary: .abs, secondary: [.shoulders, .lats, .coreStability], cat: .compound, move: .flexion, worlds: [.functionalAthletic, .cardioConditioning], equip: [.medicineBall], desc: "Slam medicine ball into ground for explosive core power.", alts: ["woodchop"], tags: ["power", "conditioning"]),
        ExerciseBuilder.make("dragon-flag", "Dragon Flag", primary: .abs, secondary: [.coreStability], cat: .bodyweight, move: .flexion, worlds: [.calisthenics], equip: [.bench], diff: .advanced, bw: true, prog: .progression, desc: "Advanced full-body lever from bench. Bruce Lee's favorite.", alts: ["hanging-leg-raise", "v-up"], tags: ["advanced", "calisthenics"]),
        ExerciseBuilder.make("l-sit", "L-Sit", primary: .abs, secondary: [.hipFlexors, .triceps], cat: .bodyweight, move: .isometric, worlds: [.calisthenics], equip: [.none], loc: .anywhere, diff: .advanced, bw: true, desc: "Static hold with legs extended parallel to ground.", alts: ["hanging-leg-raise"], tags: ["calisthenics", "isometric"]),
        ExerciseBuilder.make("hollow-body-hold", "Hollow Body Hold", primary: .abs, secondary: [.coreStability], cat: .bodyweight, move: .isometric, worlds: [.homeNoEquipment, .calisthenics, .warmupActivation], equip: [.none], loc: .anywhere, diff: .intermediate, bw: true, jointFriendly: true, desc: "Supine hold with arms overhead and legs extended, lower back pressed flat. Gymnastic core fundamental.", instructions: ["Lie on back, arms overhead", "Lift shoulders and legs off floor", "Press lower back into mat", "Hold with core braced"], cues: ["Think banana shape", "Lower back stays glued to floor"], alts: ["plank", "dead-bug"], tags: ["gymnastics", "core", "fundamental"]),
        ExerciseBuilder.make("body-saw", "Body Saw", primary: .coreStability, secondary: [.abs, .shoulders], cat: .bodyweight, move: .isometric, worlds: [.gymStrength, .calisthenics], equip: [.none], loc: .anywhere, diff: .advanced, bw: true, desc: "Forearm plank rocking forward and back. Extreme anti-extension challenge.", instructions: ["Start in forearm plank", "Rock body backward by pushing through forearms", "Return forward maintaining rigid body", "Keep hips level throughout"], alts: ["plank", "ab-wheel-rollout"], tags: ["advanced", "anti-extension"]),
        ExerciseBuilder.make("long-lever-plank", "Long Lever Plank", primary: .coreStability, secondary: [.abs, .shoulders], cat: .bodyweight, move: .isometric, worlds: [.calisthenics, .gymStrength], equip: [.none], loc: .anywhere, diff: .intermediate, bw: true, desc: "Plank with arms extended further forward for longer lever and greater core demand.", alts: ["plank", "body-saw"], tags: ["progression", "core"]),
        ExerciseBuilder.make("reverse-crunch", "Reverse Crunch", primary: .abs, cat: .bodyweight, move: .flexion, worlds: [.homeNoEquipment], equip: [.none], loc: .anywhere, diff: .beginner, beginnerOk: true, bw: true, jointFriendly: true, desc: "Curl hips off floor toward chest. Targets lower abs with minimal neck strain.", instructions: ["Lie on back, knees at 90 degrees", "Curl hips up off floor", "Bring knees toward chest", "Lower with control"], alts: ["lying-leg-raise", "hanging-leg-raise"], tags: ["lower abs", "beginner"]),
        ExerciseBuilder.make("decline-sit-up", "Decline Sit-Up", primary: .abs, secondary: [.hipFlexors], cat: .bodyweight, move: .flexion, worlds: [.gymStrength], equip: [.bench], diff: .intermediate, bw: true, desc: "Sit-up on decline bench for increased range and resistance.", alts: ["sit-up", "cable-crunch"], tags: ["abs", "loaded"]),
        ExerciseBuilder.make("plate-twist", "Plate Twist", primary: .obliques, secondary: [.abs], cat: .compound, move: .rotation, worlds: [.gymStrength, .homeGym], equip: [.none], diff: .beginner, beginnerOk: true, desc: "Seated rotation holding a weight plate. Simple loaded oblique work.", alts: ["russian-twist", "woodchop"], tags: ["obliques", "rotation"]),
    ]
}
