import Foundation

extension ExerciseLibrary {
    static let extendedMobilityExercises: [Exercise] = [
        ExerciseBuilder.make("couch-stretch", "Couch Stretch", primary: .hipFlexors, secondary: [.quads], cat: .mobility, move: .extension_, worlds: [.mobilityStretching, .recoveryRehab, .homeNoEquipment], equip: [.none], loc: .anywhere, diff: .beginner, beginnerOk: true, bw: true, jointFriendly: true, desc: "Deep hip flexor stretch with rear foot elevated against a wall.", alts: ["hip-90-90", "pigeon-stretch"], tags: ["hip flexors", "stretch", "desk worker"]),
        ExerciseBuilder.make("hamstring-stretch-standing", "Standing Hamstring Stretch", primary: .hamstrings, cat: .mobility, move: .flexion, worlds: [.mobilityStretching, .recoveryRehab, .homeNoEquipment], equip: [.none], loc: .anywhere, diff: .beginner, beginnerOk: true, bw: true, jointFriendly: true, desc: "Foot elevated on bench or step for standing hamstring stretch.", alts: ["pigeon-stretch"], tags: ["stretch", "hamstrings"]),
        ExerciseBuilder.make("figure-four-stretch", "Figure-Four Stretch", primary: .glutes, secondary: [.hipFlexors], cat: .mobility, move: .rotation, worlds: [.mobilityStretching, .recoveryRehab, .homeNoEquipment], equip: [.none], loc: .anywhere, diff: .beginner, beginnerOk: true, bw: true, jointFriendly: true, desc: "Supine piriformis and glute stretch crossing ankle over knee.", alts: ["pigeon-stretch"], tags: ["glutes", "stretch", "sciatic"]),
        ExerciseBuilder.make("doorway-chest-stretch", "Doorway Chest Stretch", primary: .chest, secondary: [.shoulders], cat: .mobility, move: .extension_, worlds: [.mobilityStretching, .recoveryRehab, .homeNoEquipment], equip: [.none], loc: .anywhere, diff: .beginner, beginnerOk: true, bw: true, jointFriendly: true, desc: "Lean through a doorway to open chest and front delts.", alts: ["shoulder-dislocate"], tags: ["posture", "chest", "stretch"]),
        ExerciseBuilder.make("child-pose", "Child's Pose", primary: .lowerBack, secondary: [.lats, .shoulders], cat: .mobility, move: .flexion, worlds: [.mobilityStretching, .recoveryRehab, .homeNoEquipment, .pilates], equip: [.none], loc: .anywhere, diff: .beginner, beginnerOk: true, bw: true, jointFriendly: true, desc: "Kneeling forward fold for back and lat relaxation.", alts: ["cat-cow"], tags: ["recovery", "relaxation", "spine"]),
        ExerciseBuilder.make("downward-dog", "Downward Dog", primary: .hamstrings, secondary: [.calves, .shoulders, .lowerBack], cat: .mobility, move: .flexion, worlds: [.mobilityStretching, .homeNoEquipment, .warmupActivation], equip: [.none], loc: .anywhere, diff: .beginner, beginnerOk: true, bw: true, jointFriendly: true, desc: "Inverted V position stretching posterior chain and shoulders.", alts: ["world-greatest-stretch"], tags: ["yoga", "full body", "stretch"]),
        ExerciseBuilder.make("scorpion-stretch", "Scorpion Stretch", primary: .hipFlexors, secondary: [.obliques, .lowerBack], cat: .mobility, move: .rotation, worlds: [.mobilityStretching, .warmupActivation], equip: [.none], loc: .anywhere, diff: .intermediate, bw: true, jointFriendly: true, desc: "Prone twist bringing foot toward opposite hand for spinal rotation.", alts: ["thoracic-rotation"], tags: ["mobility", "rotation", "warmup"]),
        ExerciseBuilder.make("foam-roll-glutes", "Foam Roll Glutes", primary: .glutes, cat: .recovery, move: .isometric, worlds: [.recoveryRehab], equip: [.foamRoller], loc: .anywhere, diff: .beginner, beginnerOk: true, bw: true, jointFriendly: true, desc: "Foam rolling the glutes for recovery and tension release.", alts: ["pigeon-stretch"], tags: ["recovery", "myofascial"]),
        ExerciseBuilder.make("foam-roll-hamstrings", "Foam Roll Hamstrings", primary: .hamstrings, cat: .recovery, move: .isometric, worlds: [.recoveryRehab], equip: [.foamRoller], loc: .anywhere, diff: .beginner, beginnerOk: true, bw: true, jointFriendly: true, desc: "Foam rolling the hamstrings for recovery.", alts: [], tags: ["recovery", "myofascial"]),
        ExerciseBuilder.make("foam-roll-lats", "Foam Roll Lats", primary: .lats, cat: .recovery, move: .isometric, worlds: [.recoveryRehab], equip: [.foamRoller], loc: .anywhere, diff: .beginner, beginnerOk: true, bw: true, jointFriendly: true, desc: "Foam rolling the lats for upper body recovery.", alts: [], tags: ["recovery", "myofascial"]),
        ExerciseBuilder.make("foam-roll-calves", "Foam Roll Calves", primary: .calves, cat: .recovery, move: .isometric, worlds: [.recoveryRehab], equip: [.foamRoller], loc: .anywhere, diff: .beginner, beginnerOk: true, bw: true, jointFriendly: true, desc: "Foam rolling the calves for ankle mobility and recovery.", alts: [], tags: ["recovery", "myofascial"]),
        ExerciseBuilder.make("ankle-circles", "Ankle Circles", primary: .calves, secondary: [.tibialis], cat: .warmup, move: .rotation, worlds: [.warmupActivation, .recoveryRehab, .homeNoEquipment], equip: [.none], loc: .anywhere, diff: .beginner, beginnerOk: true, bw: true, jointFriendly: true, desc: "Rotate ankles in circles for joint mobility.", alts: ["tibialis-raise"], tags: ["warmup", "ankle", "mobility"]),
        ExerciseBuilder.make("wrist-circles", "Wrist Circles", primary: .forearms, cat: .warmup, move: .rotation, worlds: [.warmupActivation, .recoveryRehab, .homeNoEquipment], equip: [.none], loc: .anywhere, diff: .beginner, beginnerOk: true, bw: true, jointFriendly: true, desc: "Rotate wrists in circles for joint warmup.", alts: [], tags: ["warmup", "wrists"]),
        ExerciseBuilder.make("hip-circles", "Hip Circles", primary: .hipFlexors, secondary: [.glutes], cat: .warmup, move: .rotation, worlds: [.warmupActivation, .homeNoEquipment], equip: [.none], loc: .anywhere, diff: .beginner, beginnerOk: true, bw: true, jointFriendly: true, desc: "Standing hip circles for joint mobility and warmup.", alts: ["hip-90-90", "leg-circles"], tags: ["warmup", "hips"]),
        ExerciseBuilder.make("fire-hydrant", "Fire Hydrant", primary: .glutes, secondary: [.abductors], cat: .warmup, move: .abduction, worlds: [.warmupActivation, .homeNoEquipment, .recoveryRehab], equip: [.none], loc: .anywhere, diff: .beginner, beginnerOk: true, bw: true, jointFriendly: true, desc: "On all fours, lift knee out to side for glute activation.", alts: ["clamshell", "band-walk"], tags: ["activation", "glutes"]),
        ExerciseBuilder.make("prone-scorpion", "Prone Scorpion Kicks", primary: .hipFlexors, secondary: [.lowerBack, .obliques], cat: .warmup, move: .rotation, worlds: [.warmupActivation, .mobilityStretching], equip: [.none], loc: .anywhere, diff: .beginner, beginnerOk: true, bw: true, jointFriendly: true, desc: "Lie face down, kick heel toward opposite shoulder for dynamic warm-up.", alts: ["scorpion-stretch"], tags: ["warmup", "dynamic"]),
        ExerciseBuilder.make("banded-shoulder-warmup", "Banded Shoulder Warm-Up", primary: .shoulders, secondary: [.back], cat: .warmup, move: .rotation, worlds: [.warmupActivation], equip: [.resistanceBand], loc: .anywhere, diff: .beginner, beginnerOk: true, bw: true, jointFriendly: true, desc: "Light band external rotation and pull-apart combo for shoulder prep.", alts: ["band-pull-apart", "shoulder-dislocate"], tags: ["warmup", "shoulders", "prehab"]),
        ExerciseBuilder.make("lacrosse-ball-pec", "Lacrosse Ball Pec Release", primary: .chest, cat: .recovery, move: .isometric, worlds: [.recoveryRehab], equip: [.none], loc: .anywhere, diff: .beginner, beginnerOk: true, bw: true, jointFriendly: true, desc: "Pin a lacrosse ball against wall and roll over pec for trigger point release.", alts: ["doorway-chest-stretch"], tags: ["recovery", "trigger point"]),
        ExerciseBuilder.make("wall-angel", "Wall Angel", primary: .shoulders, secondary: [.back], cat: .mobility, move: .flexion, worlds: [.mobilityStretching, .recoveryRehab, .homeNoEquipment], equip: [.none], loc: .anywhere, diff: .beginner, beginnerOk: true, bw: true, jointFriendly: true, desc: "Back against wall, slide arms up and down for thoracic and shoulder mobility.", instructions: ["Stand with back flat against wall", "Arms at 90 degrees against wall", "Slowly slide arms up overhead", "Keep contact with wall throughout"], alts: ["shoulder-dislocate"], tags: ["posture", "mobility", "office"]),
        ExerciseBuilder.make("neck-stretch-lateral", "Lateral Neck Stretch", primary: .neck, cat: .mobility, move: .flexion, worlds: [.mobilityStretching, .recoveryRehab, .homeNoEquipment], equip: [.none], loc: .anywhere, diff: .beginner, beginnerOk: true, bw: true, jointFriendly: true, desc: "Gently tilt head to side for upper trap and neck stretch.", alts: ["neck-curl"], tags: ["neck", "stretch", "desk worker"]),
        ExerciseBuilder.make("band-assisted-squat-stretch", "Band-Assisted Squat Stretch", primary: .hipFlexors, secondary: [.quads, .calves], cat: .mobility, move: .squat, worlds: [.mobilityStretching, .recoveryRehab], equip: [.resistanceBand], loc: .anywhere, diff: .beginner, beginnerOk: true, bw: true, jointFriendly: true, desc: "Deep squat hold assisted by band around rig for ankle and hip mobility.", alts: ["cossack-squat"], tags: ["mobility", "squat", "ankle"]),
        ExerciseBuilder.make("jefferson-curl", "Jefferson Curl", primary: .lowerBack, secondary: [.hamstrings], cat: .mobility, move: .flexion, worlds: [.mobilityStretching], equip: [.none], loc: .anywhere, diff: .intermediate, bw: true, jointFriendly: true, desc: "Slow standing forward fold rolling one vertebra at a time with light weight.", alts: ["spine-stretch", "romanian-deadlift"], tags: ["spinal", "flexibility", "advanced mobility"]),
    ]
}
