import Foundation

extension ExerciseLibrary {
    static let shoulderExercises: [Exercise] = [
        ExerciseBuilder.make("overhead-press", "Overhead Press", primary: .shoulders, secondary: [.triceps, .traps], move: .verticalPush, equip: [.barbell], desc: "Standing barbell press. The premier shoulder builder.", instructions: ["Grip bar at shoulder width", "Press overhead to lockout", "Lower to front of shoulders", "Keep core braced"], mistakes: ["Excessive back lean", "Flaring elbows"], cues: ["Push head through at top", "Brace core tight"], alts: ["dumbbell-shoulder-press", "machine-shoulder-press"], tags: ["strength", "compound", "mass"]),
        ExerciseBuilder.make("dumbbell-shoulder-press", "Dumbbell Shoulder Press", primary: .shoulders, secondary: [.triceps, .traps], move: .verticalPush, equip: [.dumbbell, .bench], beginnerOk: true, desc: "Seated or standing dumbbell press for shoulder development.", instructions: ["Hold dumbbells at shoulder height", "Press overhead", "Lower with control"], alts: ["overhead-press", "machine-shoulder-press"], tags: ["mass", "hypertrophy"]),
        ExerciseBuilder.make("machine-shoulder-press", "Machine Shoulder Press", primary: .shoulders, secondary: [.triceps], move: .verticalPush, equip: [.machine], beginnerOk: true, desc: "Guided shoulder press for safe, controlled pressing.", alts: ["overhead-press", "dumbbell-shoulder-press"], tags: ["beginner", "safe"]),
        ExerciseBuilder.make("arnold-press", "Arnold Press", primary: .shoulders, secondary: [.triceps], move: .verticalPush, equip: [.dumbbell], desc: "Rotating dumbbell press hitting all three delt heads.", instructions: ["Start with palms facing you", "Rotate and press overhead", "Reverse on the way down"], alts: ["dumbbell-shoulder-press"], tags: ["classic", "all delts"]),
        ExerciseBuilder.make("lateral-raise", "Lateral Raise", primary: .shoulders, cat: .isolation, move: .abduction, equip: [.dumbbell], beginnerOk: true, desc: "Essential side delt isolation for wider shoulders.", instructions: ["Hold dumbbells at sides", "Raise arms out to shoulder height", "Lead with elbows", "Lower with control"], mistakes: ["Using momentum", "Going too heavy", "Shrugging"], cues: ["Pour water out of a pitcher", "Slight forward lean"], alts: ["cable-lateral-raise", "machine-lateral-raise"], tags: ["side delts", "width"]),
        ExerciseBuilder.make("cable-lateral-raise", "Cable Lateral Raise", primary: .shoulders, cat: .isolation, move: .abduction, equip: [.cable], desc: "Constant tension lateral raise using cable.", alts: ["lateral-raise", "machine-lateral-raise"], tags: ["side delts", "isolation"]),
        ExerciseBuilder.make("machine-lateral-raise", "Machine Lateral Raise", primary: .shoulders, cat: .isolation, move: .abduction, equip: [.machine], beginnerOk: true, desc: "Machine-guided lateral raise for consistent isolation.", alts: ["lateral-raise", "cable-lateral-raise"], tags: ["beginner", "isolation"]),
        ExerciseBuilder.make("front-raise", "Front Raise", primary: .shoulders, cat: .isolation, move: .flexion, equip: [.dumbbell], desc: "Front deltoid isolation.", instructions: ["Hold dumbbell in front of thighs", "Raise to shoulder height", "Lower with control"], alts: ["cable-front-raise"], tags: ["front delts"]),
        ExerciseBuilder.make("cable-front-raise", "Cable Front Raise", primary: .shoulders, cat: .isolation, move: .flexion, equip: [.cable], desc: "Front delt raise with constant cable tension.", alts: ["front-raise"], tags: ["front delts", "cable"]),
        ExerciseBuilder.make("rear-delt-fly", "Rear Delt Fly", primary: .shoulders, secondary: [.back], cat: .isolation, move: .horizontalPull, equip: [.dumbbell], beginnerOk: true, desc: "Bent-over dumbbell fly for rear deltoids.", alts: ["face-pull", "reverse-fly-machine"], tags: ["rear delts", "posture"]),
        ExerciseBuilder.make("upright-row", "Upright Row", primary: .shoulders, secondary: [.traps], cat: .compound, move: .verticalPull, equip: [.barbell], desc: "Vertical pulling for delts and traps.", instructions: ["Grip bar narrow", "Pull up along body to chin", "Lead with elbows"], mistakes: ["Too narrow grip can impinge"], alts: ["cable-upright-row", "lateral-raise"], tags: ["traps", "delts"]),
        ExerciseBuilder.make("cable-upright-row", "Cable Upright Row", primary: .shoulders, secondary: [.traps], move: .verticalPull, equip: [.cable], desc: "Cable upright row for smoother resistance curve.", alts: ["upright-row"], tags: ["delts", "traps"]),
        ExerciseBuilder.make("shrug", "Barbell Shrug", primary: .traps, cat: .isolation, move: .verticalPull, equip: [.barbell], desc: "Heavy shrug for trap development.", instructions: ["Hold barbell at waist", "Shrug shoulders to ears", "Hold briefly at top", "Lower with control"], alts: ["dumbbell-shrug"], tags: ["traps", "mass"]),
        ExerciseBuilder.make("dumbbell-shrug", "Dumbbell Shrug", primary: .traps, cat: .isolation, move: .verticalPull, equip: [.dumbbell], beginnerOk: true, desc: "Dumbbell shrug for trap isolation.", alts: ["shrug"], tags: ["traps"]),
        ExerciseBuilder.make("pike-push-up", "Pike Push-Up", primary: .shoulders, secondary: [.triceps], cat: .bodyweight, move: .verticalPush, worlds: [.homeNoEquipment, .calisthenics], equip: [.none], loc: .anywhere, diff: .intermediate, bw: true, desc: "Bodyweight overhead press alternative.", instructions: ["Start in downward dog position", "Bend elbows lowering head to floor", "Push back up"], alts: ["overhead-press", "handstand-push-up"], tags: ["bodyweight", "overhead"]),
        ExerciseBuilder.make("handstand-push-up", "Handstand Push-Up", primary: .shoulders, secondary: [.triceps, .traps], cat: .bodyweight, move: .verticalPush, worlds: [.calisthenics], equip: [.none], loc: .anywhere, diff: .advanced, bw: true, prog: .progression, progOf: "pike-push-up", desc: "Advanced bodyweight overhead press against a wall.", alts: ["pike-push-up", "overhead-press"], tags: ["advanced", "calisthenics"]),
        ExerciseBuilder.make("band-lateral-raise", "Band Lateral Raise", primary: .shoulders, cat: .isolation, move: .abduction, worlds: [.homeNoEquipment, .homeGym], equip: [.resistanceBand], loc: .anywhere, diff: .beginner, beginnerOk: true, desc: "Resistance band lateral raise for home training.", alts: ["lateral-raise"], tags: ["home", "band"]),
        ExerciseBuilder.make("lu-raise", "Lu Raise", primary: .shoulders, secondary: [.traps], cat: .isolation, move: .flexion, equip: [.dumbbell], diff: .advanced, desc: "Front-to-lateral raise combination for full delt stimulation.", alts: ["lateral-raise", "front-raise"], tags: ["advanced", "all delts"]),
        ExerciseBuilder.make("neck-curl", "Neck Curl", primary: .neck, cat: .isolation, move: .flexion, worlds: [.gymStrength, .homeGym], equip: [.none], diff: .beginner, beginnerOk: true, bw: true, jointFriendly: true, desc: "Neck flexion exercise for neck strengthening.", alts: ["neck-extension"], tags: ["neck", "rehab"]),
        ExerciseBuilder.make("neck-extension", "Neck Extension", primary: .neck, cat: .isolation, move: .extension_, worlds: [.gymStrength, .homeGym], equip: [.none], diff: .beginner, beginnerOk: true, bw: true, jointFriendly: true, desc: "Neck extension for posterior neck strength.", alts: ["neck-curl"], tags: ["neck", "rehab"]),
        ExerciseBuilder.make("z-press", "Z-Press", primary: .shoulders, secondary: [.triceps, .coreStability], move: .verticalPush, equip: [.barbell], diff: .advanced, desc: "Seated on floor overhead press. Eliminates leg drive and demands core stability.", instructions: ["Sit on floor with legs extended", "Clean or rack barbell to shoulders", "Press overhead to lockout", "Lower with control"], cues: ["Stay upright — no leaning back", "Brace core hard"], alts: ["overhead-press", "dumbbell-shoulder-press"], tags: ["advanced", "core", "strict"]),
        ExerciseBuilder.make("smith-shoulder-press", "Smith Machine Shoulder Press", primary: .shoulders, secondary: [.triceps], move: .verticalPush, equip: [.smithMachine], beginnerOk: true, desc: "Guided shoulder press on Smith machine for safe overhead work.", alts: ["machine-shoulder-press", "overhead-press"], tags: ["guided", "beginner"]),
        ExerciseBuilder.make("elevated-pike-push-up", "Elevated Pike Push-Up", primary: .shoulders, secondary: [.triceps], cat: .bodyweight, move: .verticalPush, worlds: [.homeNoEquipment, .calisthenics], equip: [.box], loc: .anywhere, diff: .intermediate, bw: true, prog: .progression, progOf: "pike-push-up", desc: "Pike push-up with feet elevated on a box for greater overhead pressing angle.", alts: ["pike-push-up", "handstand-push-up"], tags: ["progression", "bodyweight"]),
    ]
}
