import Foundation

nonisolated extension ExerciseLibrary {
    static let armExercises: [Exercise] = [
        ExerciseBuilder.make("barbell-curl", "Barbell Curl", primary: .biceps, cat: .isolation, move: .flexion, equip: [.barbell], beginnerOk: true, desc: "Classic bicep builder with a barbell.", instructions: ["Stand with barbell at arms length", "Curl up keeping elbows pinned", "Squeeze at top", "Lower with control"], mistakes: ["Swinging body", "Moving elbows forward"], cues: ["Pin elbows to sides", "Control the negative"], alts: ["dumbbell-curl", "ez-bar-curl"], tags: ["biceps", "mass"]),
        ExerciseBuilder.make("dumbbell-curl", "Dumbbell Curl", primary: .biceps, cat: .isolation, move: .flexion, equip: [.dumbbell], beginnerOk: true, desc: "Fundamental dumbbell bicep curl.", instructions: ["Hold dumbbells at sides", "Curl up with supinated grip", "Squeeze at top", "Lower slowly"], alts: ["barbell-curl", "hammer-curl"], tags: ["biceps", "fundamental"]),
        ExerciseBuilder.make("hammer-curl", "Hammer Curl", primary: .biceps, secondary: [.forearms], cat: .isolation, move: .flexion, equip: [.dumbbell], beginnerOk: true, desc: "Neutral grip curl targeting brachialis and forearms.", instructions: ["Hold dumbbells with neutral grip", "Curl up keeping palms facing each other", "Lower with control"], alts: ["dumbbell-curl", "cross-body-curl"], tags: ["brachialis", "forearms"]),
        ExerciseBuilder.make("ez-bar-curl", "EZ-Bar Curl", primary: .biceps, cat: .isolation, move: .flexion, equip: [.barbell], beginnerOk: true, jointFriendly: true, desc: "Angled bar curl that's easier on the wrists.", alts: ["barbell-curl", "dumbbell-curl"], tags: ["wrist-friendly"]),
        ExerciseBuilder.make("preacher-curl", "Preacher Curl", primary: .biceps, cat: .isolation, move: .flexion, equip: [.barbell, .bench], desc: "Strict curl on preacher bench eliminating momentum.", alts: ["concentration-curl", "machine-curl"], tags: ["strict", "isolation"]),
        ExerciseBuilder.make("concentration-curl", "Concentration Curl", primary: .biceps, cat: .isolation, move: .flexion, equip: [.dumbbell], beginnerOk: true, desc: "Seated single-arm curl for peak contraction.", alts: ["preacher-curl", "dumbbell-curl"], tags: ["peak", "isolation"]),
        ExerciseBuilder.make("cable-curl", "Cable Curl", primary: .biceps, cat: .isolation, move: .flexion, equip: [.cable], desc: "Constant tension bicep curl with cable.", alts: ["barbell-curl", "dumbbell-curl"], tags: ["cable", "constant tension"]),
        ExerciseBuilder.make("incline-dumbbell-curl", "Incline Dumbbell Curl", primary: .biceps, cat: .isolation, move: .flexion, equip: [.dumbbell, .bench], desc: "Incline bench curl for a deep bicep stretch.", alts: ["dumbbell-curl"], tags: ["stretch", "long head"]),
        ExerciseBuilder.make("spider-curl", "Spider Curl", primary: .biceps, cat: .isolation, move: .flexion, equip: [.dumbbell, .bench], desc: "Prone incline curl for peak contraction focus.", alts: ["preacher-curl"], tags: ["peak", "short head"]),
        ExerciseBuilder.make("cross-body-curl", "Cross-Body Hammer Curl", primary: .biceps, secondary: [.forearms], cat: .isolation, move: .flexion, equip: [.dumbbell], desc: "Hammer curl across the body for brachialis.", alts: ["hammer-curl"], tags: ["brachialis"]),
        ExerciseBuilder.make("machine-curl", "Machine Bicep Curl", primary: .biceps, cat: .isolation, move: .flexion, equip: [.machine], beginnerOk: true, desc: "Guided bicep curl machine.", alts: ["barbell-curl", "dumbbell-curl"], tags: ["beginner", "machine"]),
        ExerciseBuilder.make("band-curl", "Resistance Band Curl", primary: .biceps, cat: .isolation, move: .flexion, worlds: [.homeNoEquipment, .homeGym], equip: [.resistanceBand], loc: .anywhere, diff: .beginner, beginnerOk: true, desc: "Home-friendly bicep curl with resistance band.", alts: ["dumbbell-curl"], tags: ["home", "band"]),
        ExerciseBuilder.make("tricep-pushdown", "Tricep Pushdown", primary: .triceps, cat: .isolation, move: .extension_, equip: [.cable], beginnerOk: true, desc: "Cable pushdown for tricep isolation. Staple arm exercise.", instructions: ["Grip rope or bar at chest height", "Push down extending elbows", "Squeeze triceps at bottom", "Return with control"], mistakes: ["Flaring elbows", "Leaning forward too much"], cues: ["Pin elbows to sides", "Spread rope at bottom"], alts: ["overhead-tricep-extension", "skull-crusher"], tags: ["triceps", "fundamental"]),
        ExerciseBuilder.make("overhead-tricep-extension", "Overhead Tricep Extension", primary: .triceps, cat: .isolation, move: .extension_, equip: [.dumbbell], desc: "Overhead extension for long head emphasis.", instructions: ["Hold dumbbell overhead with both hands", "Lower behind head bending elbows", "Extend back up", "Keep elbows close"], alts: ["tricep-pushdown", "skull-crusher"], tags: ["long head"]),
        ExerciseBuilder.make("skull-crusher", "Skull Crusher", primary: .triceps, cat: .isolation, move: .extension_, equip: [.barbell, .bench], desc: "Lying tricep extension. Classic mass builder.", instructions: ["Lie on bench holding bar overhead", "Lower bar to forehead by bending elbows", "Extend back up"], mistakes: ["Flaring elbows", "Moving upper arms"], alts: ["tricep-pushdown", "overhead-tricep-extension"], tags: ["mass", "classic"]),
        ExerciseBuilder.make("close-grip-bench", "Close-Grip Bench Press", primary: .triceps, secondary: [.chest, .shoulders], move: .horizontalPush, equip: [.barbell, .bench], desc: "Narrow grip bench press emphasizing triceps.", instructions: ["Grip bar shoulder width or narrower", "Lower to lower chest", "Press up focusing on tricep contraction"], alts: ["diamond-push-up", "tricep-pushdown"], tags: ["compound", "mass"]),
        ExerciseBuilder.make("tricep-kickback", "Tricep Kickback", primary: .triceps, cat: .isolation, move: .extension_, equip: [.dumbbell], beginnerOk: true, desc: "Bent-over tricep extension with dumbbell.", instructions: ["Hinge forward with arm at 90 degrees", "Extend arm fully back", "Squeeze at top", "Lower with control"], alts: ["tricep-pushdown"], tags: ["isolation", "peak"]),
        ExerciseBuilder.make("cable-overhead-extension", "Cable Overhead Extension", primary: .triceps, cat: .isolation, move: .extension_, equip: [.cable], desc: "Cable overhead extension for long head tricep.", alts: ["overhead-tricep-extension"], tags: ["long head", "cable"]),
        ExerciseBuilder.make("dip-tricep", "Tricep Dip", primary: .triceps, secondary: [.chest, .shoulders], cat: .bodyweight, move: .verticalPush, worlds: [.gymStrength, .calisthenics], equip: [.dipStation], diff: .intermediate, bw: true, desc: "Upright dips emphasizing triceps over chest.", alts: ["bench-dip", "close-grip-bench"], tags: ["compound", "bodyweight"]),
        ExerciseBuilder.make("wrist-curl", "Wrist Curl", primary: .forearms, cat: .isolation, move: .flexion, equip: [.dumbbell], beginnerOk: true, jointFriendly: true, desc: "Seated wrist curl for forearm flexor development.", alts: ["reverse-wrist-curl"], tags: ["forearms", "grip"]),
        ExerciseBuilder.make("reverse-wrist-curl", "Reverse Wrist Curl", primary: .forearms, cat: .isolation, move: .extension_, equip: [.dumbbell], beginnerOk: true, jointFriendly: true, desc: "Reverse wrist curl for forearm extensor development.", alts: ["wrist-curl"], tags: ["forearms"]),
        ExerciseBuilder.make("farmer-walk", "Farmer's Walk", primary: .forearms, secondary: [.traps, .coreStability], cat: .compound, move: .carry, worlds: [.gymStrength, .functionalAthletic], equip: [.dumbbell], desc: "Loaded carry for grip, traps, and total body.", instructions: ["Pick up heavy dumbbells", "Walk with tall posture", "Maintain grip"], alts: ["dead-hang"], tags: ["grip", "functional", "conditioning"]),
        ExerciseBuilder.make("dead-hang", "Dead Hang", primary: .forearms, secondary: [.lats], cat: .bodyweight, move: .isometric, worlds: [.calisthenics, .recoveryRehab], equip: [.pullUpBar], diff: .beginner, beginnerOk: true, bw: true, jointFriendly: true, desc: "Passive hang from pull-up bar for grip and shoulder health.", alts: ["farmer-walk"], tags: ["grip", "shoulder health", "decompression"]),
        ExerciseBuilder.make("bayesian-curl", "Bayesian Cable Curl", primary: .biceps, cat: .isolation, move: .flexion, equip: [.cable], desc: "Cable curl with arm behind body for maximal long head stretch.", instructions: ["Stand facing away from low cable", "Arm extended behind body holding handle", "Curl forward squeezing bicep", "Return with control"], cues: ["Keep elbow behind torso", "Full stretch at bottom"], alts: ["incline-dumbbell-curl", "cable-curl"], tags: ["long head", "stretch", "advanced"]),
        ExerciseBuilder.make("cable-hammer-curl", "Cable Hammer Curl", primary: .biceps, secondary: [.forearms], cat: .isolation, move: .flexion, equip: [.cable], desc: "Rope attachment hammer curl on cable for constant tension on brachialis.", alts: ["hammer-curl", "cable-curl"], tags: ["brachialis", "cable"]),
        ExerciseBuilder.make("overhead-cable-curl", "Overhead Cable Curl", primary: .biceps, cat: .isolation, move: .flexion, equip: [.cable], desc: "High cable curl with arms spread. Peak contraction isolation.", instructions: ["Set cables high, stand centered", "Curl handles toward ears", "Squeeze hard at peak", "Extend with control"], alts: ["cable-curl"], tags: ["peak", "isolation", "show"]),
        ExerciseBuilder.make("jm-press", "JM Press", primary: .triceps, secondary: [.chest], cat: .compound, move: .extension_, equip: [.barbell, .bench], diff: .advanced, desc: "Hybrid skull crusher and close-grip bench. Elite tricep mass builder.", instructions: ["Lie on bench with close grip", "Lower bar to upper chest/chin area", "Elbows stay pointed forward", "Press to lockout"], alts: ["skull-crusher", "close-grip-bench"], tags: ["advanced", "mass", "powerlifting"]),
    ]
}
