#!/usr/bin/env python3
"""Merge curated German STRQ copy into ios/STRQ/Localizable.xcstrings.

This script keeps Localizable.xcstrings as the single source of truth for the
main iOS app localization. It adds missing keys and updates existing German
values with natural STRQ copy.
"""

from __future__ import annotations

import json
from collections import OrderedDict
from pathlib import Path

CATALOG_PATH = Path("ios/STRQ/Localizable.xcstrings")

DE: dict[str, str] = {
    # Core navigation and onboarding
    "Today": "Heute",
    "Coach": "Coach",
    "Plan": "Plan",
    "Progress": "Fortschritt",
    "Profile": "Profil",
    "Train": "Training",
    "Training": "Training",
    "Settings": "Einstellungen",
    "Get Started": "Los geht’s",
    "Continue": "Weiter",
    "Build My Plan": "Meinen Plan erstellen",
    "Your intelligent training companion": "Dein smarter Trainingsbegleiter",
    "Adaptive coaching that learns from you": "Adaptives Coaching, das mit dir lernt",
    "Smart progression & plateau detection": "Smarte Progression & Plateau-Erkennung",
    "Plans that evolve week by week": "Pläne, die sich Woche für Woche anpassen",
    "About You": "Über dich",
    "Your Name": "Dein Name",
    "Enter your name": "Name eingeben",
    "Body Metrics": "Körperdaten",
    "Your Starting Point": "Dein Startpunkt",
    "This is your baseline. STRQ tracks progress from here.": "Das ist deine Basis. STRQ misst deinen Fortschritt ab hier.",
    "Target Weight (optional)": "Zielgewicht (optional)",
    "Body Fat % (optional)": "Körperfett % (optional)",
    "Not set": "Nicht festgelegt",
    "Your Goal": "Dein Ziel",
    "Training Experience": "Trainingserfahrung",
    "Training Setup": "Training-Setup",
    "Muscle Focus": "Muskelfokus",
    "Lifestyle & Recovery": "Lifestyle & Regeneration",
    "Check in": "Check-in",
    "Start Session 1": "Session 1 starten",
    "Start Workout": "Training starten",
    "Resume Workout": "Training fortsetzen",
    "Your Plan is Ready": "Dein Plan ist bereit",
    "Start Session 1 now. STRQ will tune the rest from real training.": "Starte jetzt Session 1. STRQ passt den Rest anhand deines echten Trainings an.",
    "You'll go straight into today's session. You can fine-tune the plan later in Train.": "Du startest direkt mit der heutigen Einheit. Deinen Plan kannst du später unter Training anpassen.",

    # General app copy
    "Athlete": "Athlet",
    "Ready": "Bereit",
    "Review": "Review",
    "Next": "Als Nächstes",
    "Done": "Fertig",
    "Save": "Speichern",
    "Delete": "Löschen",
    "Reset": "Zurücksetzen",
    "Keep": "Behalten",
    "Cancel": "Abbrechen",
    "OK": "OK",
    "Saved": "Gespeichert",
    "Unavailable": "Nicht verfügbar",
    "JUST COMPLETED": "GERADE BEENDET",
    "STRQ took": "STRQ hat",
    "JUST NOW": "GERADE EBEN",
    "YESTERDAY": "GESTERN",
    "CALIBRATING": "KALIBRIERT",
    "TODAY": "HEUTE",

    # Training and workout language
    "Exercises": "Übungen",
    "Exercise": "Übung",
    "Duration": "Dauer",
    "Total Sets": "Sätze gesamt",
    "Training Week": "Trainingswoche",
    "Rest": "Pause",
    "Recovery": "Regeneration",
    "Recovery Day": "Erholungstag",
    "Rest, eat well, and come back stronger.": "Erhol dich, iss gut und komm stärker zurück.",
    "This Week": "Diese Woche",
    "Sessions": "Einheiten",
    "Volume": "Volumen",
    "Protein": "Protein",
    "Sleep": "Schlaf",
    "Workout options": "Trainingsoptionen",
    "Save & Leave": "Speichern & schließen",
    "Continue Workout": "Training fortsetzen",
    "Discard Workout?": "Training verwerfen?",
    "Discard Workout": "Training verwerfen",
    "Keep Workout": "Training behalten",
    "All logged sets for this session will be lost. This can't be undone.": "Alle eingetragenen Sätze dieser Einheit gehen verloren. Das kann nicht rückgängig gemacht werden.",
    "Save & Leave keeps this workout ready to resume from Today.": "Speichern & schließen hält dieses Training auf der Heute-Seite zum Fortsetzen bereit.",
    "Finish Workout": "Training beenden",
    "Finish workout": "Training beenden",
    "Save & Leave preserves everything you've logged and keeps this workout ready to resume from Today.": "Speichern & schließen behält alles, was du eingetragen hast, und hält dieses Training auf der Heute-Seite zum Fortsetzen bereit.",
    "EX %d/%d": "ÜB %d/%d",
    "SET %d/%d": "SATZ %d/%d",
    "Target %@": "Ziel %@",
    "%ds rest": "%ds Pause",
    "PREV": "LETZTES",
    "BEST": "BESTE",
    "TARGET": "ZIEL",
    "no data": "keine Daten",
    "BW": "BW",
    "WEIGHT": "GEWICHT",
    "ADDED LOAD": "ZUSATZGEWICHT",
    "REPS": "WDH.",
    "kg added": "kg Zusatz",
    "kg": "kg",
    "reps": "Wdh.",
    "Edit Weight": "Gewicht bearbeiten",
    "Edit Reps": "Wdh. bearbeiten",
    "Log Set %d": "Satz %d eintragen",
    "Last exercise complete": "Letzte Übung abgeschlossen",
    "Exercise complete": "Übung abgeschlossen",
    "Finish Workout when you're ready to save this session.": "Beende das Training, wenn du diese Einheit speichern möchtest.",
    "Move to the next exercise when you're ready.": "Gehe zur nächsten Übung, wenn du bereit bist.",
    "Match last": "Letzten übernehmen",
    "Target": "Ziel",

    # Training plan
    "Edit Session": "Einheit bearbeiten",
    "Schedule": "Zeitplan",
    "Exercise Library": "Übungsbibliothek",
    "Search exercises": "Übungen suchen",
    "Review & Start": "Prüfen & starten",
    "DAY %d": "TAG %d",
    "Skipped": "Übersprungen",
    "Sets": "Sätze",
    "Time": "Dauer",
    "Effort": "Intensität",
    "Warm-Up": "Warm-up",
    "Key Lifts": "Hauptübungen",
    "Support": "Assistenz",
    "Accessory": "Zusatz",
    "%d · %d sets": "%d · %d Sätze",
    "CUSTOM": "ANGEPASST",
    "Edit Prescription": "Vorgabe bearbeiten",
    "Swap Exercise": "Übung ersetzen",
    "Restore Coach Default": "Coach-Standard wiederherstellen",
    "Remove": "Entfernen",
    "Undo": "Rückgängig",
    "Revert": "Zurücksetzen",
    "Deload Week": "Deload-Woche",
    "Coach-Adjusted Week": "Woche angepasst",
    "Volume Reduced": "Volumen reduziert",
    "Exercise Swapped": "Übung ersetzt",
    "Lighter Session": "Leichtere Einheit",
    "Week Regenerated": "Woche neu geplant",
    "Unskip": "Wieder einplanen",
    "Skip": "Überspringen",
    "Move": "Verschieben",
    "No Plan Yet": "Noch kein Plan",
    "Complete onboarding to generate\nyour personalized training plan.": "Schließe das Onboarding ab, um\ndeinen persönlichen Trainingsplan zu erstellen.",

    # Body, progress, nutrition
    "Height": "Größe",
    "Weight": "Gewicht",
    "Age": "Alter",
    "Gender": "Geschlecht",
    "How are you feeling?": "Wie fühlst du dich?",
    "Quick check-in to optimize today": "Kurzer Check-in für heute",
    "Body Check-In": "Körper-Check-in",
    "Quick weigh-in to keep your progress on track": "Kurzer Wiege-Check, damit dein Fortschritt im Blick bleibt",
    "Log Weight": "Gewicht eintragen",
    "Log weight": "Gewicht eintragen",
    "Track your body weight": "Körpergewicht tracken",
    "Body Fat (optional)": "Körperfett (optional)",
    "Current": "Aktuell",
    "Start": "Start",
    "Change": "Änderung",
    "Insights": "Insights",
    "Good morning": "Guten Morgen",
    "Good afternoon": "Guten Tag",
    "Good evening": "Guten Abend",
    "Late night": "Noch wach?",
    "Body Progress": "Körperfortschritt",
    "Log Today": "Heute eintragen",
    "Body Weight": "Körpergewicht",
    "Recent Weigh-Ins": "Letzte Wiege-Checks",
    "Body & Nutrition": "Körper & Ernährung",
    "Edit Targets": "Ziele bearbeiten",
    "Sleep Log": "Schlaf eintragen",
    "Calories": "Kalorien",
    "Maintaining": "Halten",

    # Notifications settings
    "Notifications": "Benachrichtigungen",
    "Stay on Track": "Dranbleiben",
    "Enable Reminders": "Erinnerungen aktivieren",
    "Notifications Off": "Benachrichtigungen aus",
    "Smart reminders timed to your real schedule": "Smarte Erinnerungen passend zu deinem echten Plan",
    "Turn on in Settings to receive STRQ reminders": "Aktiviere sie in den Einstellungen, um STRQ-Erinnerungen zu erhalten",
    "Let STRQ remind you at the right moments": "Lass dich von STRQ im richtigen Moment erinnern",
    "Enable": "Aktivieren",
    "Workout Reminders": "Trainingserinnerungen",
    "Workout Planned Today": "Training heute geplant",
    "Get reminded when you have a session scheduled": "Erhalte eine Erinnerung, wenn eine Einheit geplant ist",
    "Reminder Time": "Erinnerungszeit",
    "Daily Check-In": "Täglicher Check-in",
    "Daily Readiness Check-In": "Täglicher Readiness-Check-in",
    "Morning reminder to log how you're feeling": "Morgendliche Erinnerung für deinen kurzen Check-in",
    "Check-In Time": "Check-in-Zeit",
    "Weekly Review": "Wochenreview",
    "Weekly Review Ready": "Wochenreview bereit",
    "Get notified when your weekly check-in is available": "Benachrichtigung, sobald dein Wochenreview bereit ist",
    "Review Day": "Review-Tag",
    "Coach Nudges": "Coach-Hinweise",
    "Coach Recommendations": "Coach-Empfehlungen",
    "When your coach has important adjustments or insights": "Wenn dein Coach wichtige Anpassungen oder Insights hat",
    "Streak Protection": "Streak-Schutz",
    "Streak at Risk": "Streak gefährdet",
    "Reminder when your streak might break tomorrow": "Erinnerung, wenn dein Streak morgen reißen könnte",
    "Sync with Apple Health": "Mit Apple Health synchronisieren",
    "Read body weight and sleep, write workouts and weigh-ins": "Körpergewicht und Schlaf lesen, Workouts und Wiege-Checks speichern",
    "Sunday": "Sonntag",
    "Monday": "Montag",
    "Tuesday": "Dienstag",
    "Wednesday": "Mittwoch",
    "Thursday": "Donnerstag",
    "Friday": "Freitag",
    "Saturday": "Samstag",

    # Scheduled notifications
    "Morning check-in": "Morgen-Check-in",
    "Weekly review ready": "Wochenreview bereit",
    "Your session is ready": "Deine Einheit ist bereit",
    "Back when you're ready": "Weiter, wenn du bereit bist",
    "Weekly weigh-in": "Wöchentlicher Wiege-Check",
    "Log last night's sleep": "Schlaf der letzten Nacht eintragen",
    "notification.workout.today.title": "Heute: %@",
    "notification.workout.tomorrow.title": "Morgen: %@",
    "notification.workout.next.early.body": "Die nächste Einheit macht deine Basis genauer. Kleine Schritte summieren sich.",
    "notification.workout.next.body": "Bereite dich auf %@ vor. Schlaf und Energie machen den Unterschied.",
    "notification.workout.first_session.body": "Deine erste Einheit setzt die Basis. Halte es heute sauber und einfach.",
    "notification.workout.focus_ready.body": "Deine Regeneration passt – %@ steht an. Fokus auf saubere Wiederholungen.",
    "notification.workout.ready.body": "Regeneration und Progression passen zusammen. Zeit fürs Training.",
    "notification.workout.low_readiness.body": "Deine Readiness ist heute niedriger. Saubere Ausführung vor Gewicht.",
    "notification.workout.focus_default.body": "%@ steht heute an. %@ ist bereit.",
    "notification.workout.default.body": "%@ ist bereit.",
    "notification.readiness.early.body": "Sag STRQ kurz, wie sich dein Tag anfühlt. So wird dein Plan genauer.",
    "notification.readiness.body": "Wie fühlt sich dein Körper heute an? 30 Sekunden schärfen deine Einheit.",
    "notification.weekly_review.ready.body": "Deine Woche ist drin. Sieh dir an, was sich bewegt hat – und was als Nächstes kommt.",
    "notification.weekly_review.default.body": "Schließ die Woche mit einem klaren Review ab.",
    "notification.streak.title": "Halte deinen %d-Tage-Streak",
    "notification.streak.body": "Ein Check-in oder eine kurze Einheit reicht, um dranzubleiben.",
    "notification.weight_log.body": "Ein kurzer Eintrag hält deinen Verlauf sauber.",
    "notification.sleep_log.body": "Schlaf ist ein wichtiger Teil deiner Regeneration. Dauert nur kurz.",
    "notification.comeback.in_rhythm.early.body": "Eine saubere Einheit bringt den Rhythmus zurück.",
    "notification.comeback.in_rhythm.body": "Eine Einheit reicht, um deinen Plan im Rhythmus zu halten. Kein Druck.",
    "notification.comeback.pause.title": "Mach dort weiter, wo du aufgehört hast",
    "notification.comeback.pause.body": "Ein paar Tage Pause sind okay. Deine nächste Einheit bleibt der richtige Schritt – kein Neustart nötig.",
    "notification.comeback.extended.title": "Steig kontrolliert wieder ein",
    "notification.comeback.extended.body": "STRQ macht deine erste Einheit zurück leichter. Ein sauberer Einstieg hält länger.",
    "notification.comeback.long.title": "Aufbauen, nicht testen",
    "notification.comeback.long.body": "Behandle diese Woche wie einen Aufbau-Block. Leichtere Einheiten jetzt zahlen sich später aus.",

    # Profile, account, sync, store
    "Reset All Data": "Alle Daten zurücksetzen",
    "Reset All Data?": "Alle Daten zurücksetzen?",
    "This will clear all your data and restart onboarding.": "Alle Daten werden gelöscht und das Onboarding startet neu.",
    "Your training stays on this device. You can sign in again later to sync or restore from iCloud.": "Dein Training bleibt auf diesem Gerät. Du kannst dich später erneut anmelden, um mit iCloud zu synchronisieren oder wiederherzustellen.",
    "Restore from iCloud": "Aus iCloud wiederherstellen",
    "Restore This Device?": "Dieses Gerät wiederherstellen?",
    "Restore This Device": "Dieses Gerät wiederherstellen",
    "This will replace data on this device with your most recent iCloud snapshot.": "Dadurch werden die Daten auf diesem Gerät durch deinen neuesten iCloud-Stand ersetzt.",
    "Your training data has been restored.": "Deine Trainingsdaten wurden wiederhergestellt.",
    "No cloud snapshot found yet. Train on this device and it will sync automatically.": "Noch kein iCloud-Stand gefunden. Trainiere auf diesem Gerät, dann wird automatisch synchronisiert.",
    "This device has been updated from your latest iCloud snapshot.": "Dieses Gerät wurde mit deinem neuesten iCloud-Stand aktualisiert.",
    "No iCloud snapshot is available yet. Once you train while signed in, changes will sync automatically.": "Es ist noch kein iCloud-Stand verfügbar. Sobald du angemeldet trainierst, werden Änderungen automatisch synchronisiert.",
    "iCloud isn't available right now. Check that iCloud is enabled, then try again.": "iCloud ist gerade nicht verfügbar. Prüfe, ob iCloud aktiviert ist, und versuche es erneut.",
    "This device is already using your latest iCloud data.": "Dieses Gerät nutzt bereits deinen neuesten iCloud-Stand.",
    "We couldn't read your iCloud data right now. Try again in a moment.": "Deine iCloud-Daten konnten gerade nicht gelesen werden. Versuche es gleich noch einmal.",
    "Use your most recent iCloud snapshot on this device. Current local data will be replaced.": "Nutze deinen neuesten iCloud-Stand auf diesem Gerät. Die aktuellen lokalen Daten werden ersetzt.",
    "iCloud Sync": "iCloud-Sync",
    "Sync & Restore": "Sync & Wiederherstellung",
    "Replace local data with your latest iCloud snapshot": "Lokale Daten durch deinen neuesten iCloud-Stand ersetzen",
    "Sign in with Apple to keep your training backed up in iCloud and ready to restore on another device.": "Melde dich mit Apple an, um dein Training in iCloud zu sichern und auf einem anderen Gerät wiederherstellen zu können.",
    "Your training stays local on this device until you turn sync on.": "Dein Training bleibt lokal auf diesem Gerät, bis du Sync aktivierst.",
    "Signed in with Apple": "Mit Apple angemeldet",
    "Signed in as %@": "Angemeldet als %@",
    "Sign in with Apple to back up your training to iCloud.": "Melde dich mit Apple an, um dein Training in iCloud zu sichern.",
    "Sign Out": "Abmelden",
    "Sign Out?": "Abmelden?",
    "iCloud isn't available right now": "iCloud ist gerade nicht verfügbar",
    "iCloud unavailable": "iCloud nicht verfügbar",
    "iCloud unavailable on this device": "iCloud ist auf diesem Gerät nicht verfügbar",
    "Ready to sync": "Bereit zum Synchronisieren",
    "Syncing…": "Synchronisiert…",
    "Saving recent changes": "Aktuelle Änderungen werden gespeichert",
    "Some changes couldn't be saved to iCloud yet": "Einige Änderungen konnten noch nicht in iCloud gespeichert werden",
    "Sync paused. Try again shortly": "Sync pausiert. Versuche es gleich erneut",
    "Last synced %@": "Zuletzt synchronisiert %@",
    "Changes sync automatically": "Änderungen werden automatisch synchronisiert",
    "OFF": "AUS",
    "SYNC": "SYNC",
    "CHECK": "PRÜFEN",
    "ON": "AN",
    "STRQ Pro": "STRQ Pro",
    "Deeper coaching, plans that evolve, full ecosystem.": "Mehr Coaching, adaptive Pläne und volles Ökosystem.",
    "Adaptive": "Adaptiv",
    "Evolving": "Dynamisch",
    "Sync": "Sync",
    "Watch": "Watch",
    "Days / Week": "Tage/Woche",
    "Session Length": "Dauer pro Einheit",
    "Split": "Split",
    "Location": "Trainingsort",
    "Focus:": "Fokus:",
    "Physique & Nutrition Coaching": "Körper- & Ernährungscoaching",
    "STRQ uses weigh-ins and nutrition logs to read body-composition progress.": "STRQ nutzt Gewicht und Ernährungseinträge, um deine Körperentwicklung besser einzuordnen.",
    "Optional. Training and recovery coaching stay fully active without food or bodyweight logs.": "Optional. Trainings- und Recovery-Coaching bleiben auch ohne Gewicht oder Ernährung aktiv.",
    "Coaching Style": "Coaching-Stil",
    "PERSONAL": "PERSÖNLICH",
    "Notifications & Tools": "Benachrichtigungen & Tools",
    "Danger Zone": "Kritischer Bereich",
    "Privacy": "Datenschutz",
    "Terms": "Nutzungsbedingungen",
    "Support": "Support",
    "Your setup is locked in. STRQ is building its first read on your training rhythm.": "Dein Setup steht. STRQ lernt jetzt deinen Trainingsrhythmus kennen.",
    "Your coaching profile, recovery context, and continuity settings in one place.": "Dein Coaching-Profil, deine Recovery und deine Einstellungen an einem Ort.",
    "Restore Purchases": "Käufe wiederherstellen",
    "Purchases restored successfully.": "Käufe erfolgreich wiederhergestellt.",
    "No active subscriptions found.": "Keine aktiven Abos gefunden.",
    "Subscriptions are not available in this environment.": "Abos sind in dieser Umgebung nicht verfügbar.",
    "Manage Subscription": "Abo verwalten",
    "Subscriptions coming soon": "Abos bald verfügbar",
    "Premium plans will appear here once App Store setup is complete.": "Premium-Pläne erscheinen hier, sobald die App-Store-Einrichtung abgeschlossen ist.",
    "Personal Records": "Bestleistungen",
    "Consistency": "Konstanz",
    "Strength": "Kraft",
    "Goal": "Ziel",
    "Training Level": "Trainingslevel",
    "Days per Week": "Tage pro Woche",
}


def localized_unit(value: str) -> dict:
    return {
        "localizations": {
            "de": {
                "stringUnit": {
                    "state": "translated",
                    "value": value,
                }
            }
        }
    }


def main() -> None:
    if not CATALOG_PATH.exists():
        raise FileNotFoundError(f"Missing string catalog: {CATALOG_PATH}")

    catalog = json.loads(CATALOG_PATH.read_text(encoding="utf-8"), object_pairs_hook=OrderedDict)
    catalog.setdefault("sourceLanguage", "en")
    catalog.setdefault("version", "1.0")
    strings = catalog.setdefault("strings", OrderedDict())

    for key, value in DE.items():
        entry = strings.setdefault(key, OrderedDict())
        localizations = entry.setdefault("localizations", OrderedDict())
        de = localizations.setdefault("de", OrderedDict())
        de["stringUnit"] = OrderedDict([
            ("state", "translated"),
            ("value", value),
        ])

    CATALOG_PATH.write_text(
        json.dumps(catalog, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
